#!/usr/bin/env python3 
def align80(dna,limit):
	dna_strip=dna.strip()
	dna_new=dna_strip.replace('\n','')#this will replace empty lines with nothing	
	dna_sub="" #creates an empty folder
	for position in range(0,len(dna_new),limit):#creates a range with positions
		#print(position)
		dna_sub=dna_sub+dna_new[position:position+limit]+'\n'#you need to add it to sub_dna and the range needs to keep adding 80	
	#print(dna_sub)
	return dna_sub
dna1 = '''GATGGGATTGGGGTTTTCCCCTCCCATGTGCTCAAGACTGGCGCTAAAAGTTTTGAGCTTCTCAAAAGTCTAGAGCCACC
GTCCAGGGAGCAGGTAGCTGCTGGGCTCCGGGGACACTTTGCGTTCGGGCTGGGAGCGTGCTTTCCACGACGGTGACACG
CTTCCCTGGATTGGCAGCCAGACTGCCTTCCGGGTCACTGCCATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGCCCCC
TCTGAGTCAGGAAACATTTTCAGACCTATGGAAACTACTTCCTGAAAACAACGTTCTGTCCCCCTTGCCGTCCCAAGCAA
TGGATGATTTGATGCTGTCCCCGGACGATATTGAACAATGGTTCACTGAAGACCCAGGTCCAGATGAAGCTCCCAGAATG
CCAGAGGCTGCTCCCCCCGTGGCCCCTGCACCAGCAGCTCCTACACCGGCGGCCCCTGCACCAGCCCCCTCCTGGCCCCT
GTCATCTTCT'''
limit1=80
y=align80(dna1,limit1)
print(y)		 
		
			

